# this tells that we need super user permission to execute travis
sudo: required 

#it tells travis that we need docker
services:
  - docker


#deployable commands
deploy:
  provider: elasticbeanstalk
  #region we created the elasticbeanstalk
  region: "us-east-2"
  # app name
  app: "sample"
  #env name from AWS
  env: "Sample-env"
  #travis zip the all the code files and deplou it to s3 and thats the bucket name 
  #this is automatically created by beanstalk
  bucket_name: "elasticbeanstalk-us-east-2-776697933493"
  #path is initially same as app name
  bucker_path: "sample"
  #only deploy when master brach get code
  on:
    branch: master
    #add env secrets in travis and place it here
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"



  
  


